import { useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import '../App.css'
import type { BlogPost } from './types'
import { getPost } from './api'

function BlogDetailPage() {
  const { id } = useParams<{ id: string }>()
  const [post, setPost] = useState<BlogPost | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!id) return

    let cancelled = false

    async function load() {
      try {
        const data = await getPost(id)
        if (!cancelled) {
          setPost(data)
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load post.')
        }
      } finally {
        if (!cancelled) {
          setLoading(false)
        }
      }
    }

    load()

    return () => {
      cancelled = true
    }
  }, [id])

  return (
    <section className="section">
      <div className="blog-detail-header">
        <div>
          <h2>{post?.title ?? 'Blog post'}</h2>
          {post?.createdAt && (
            <p className="blog-card-meta">
              {new Date(post.createdAt).toLocaleDateString()}
            </p>
          )}
        </div>
        <Link to="/blog" className="blog-link">
          ← Back to all posts
        </Link>
      </div>

      {loading && <p>Loading post…</p>}

      {!loading && error && <p className="blog-error">Could not load this post. Please try again.</p>}

      {!loading && !error && !post && <p className="blog-error">Post not found.</p>}

      {!loading && !error && post && (
        <article className="blog-detail-body">
          {post.tags && post.tags.length > 0 && (
            <div className="blog-tags">
              {post.tags.map((tag) => (
                <span key={tag} className="blog-tag">
                  {tag}
                </span>
              ))}
            </div>
          )}
          <div
            className="blog-content"
            // content is HTML generated by the editor
            dangerouslySetInnerHTML={{ __html: post.content }}
          />
        </article>
      )}
    </section>
  )
}

export default BlogDetailPage

